name: Manga-Auto-Update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # استخدمنا الإصدار 4 الأحدث

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # استخدم إصدار 20 المستقر

      - name: Install dependencies
        run: |
          npm init -y
          npm install axios cheerio @supabase/supabase-js
        
      - name: Run Scraper
        run: node scraper.js
